name: socialapp

packages:
  - apps/*
  - packages/*
  - packages/features/*

scripts:
  analyze:
    run: melos exec -c 1 --flutter -- "flutter analyze"
    description: Analyze every Flutter app and package.
  test:
    run: melos exec -c 1 --flutter --dir-exists=test -- "flutter test"
    description: Test every Flutter app and package that has tests.
  gen:
    run: melos exec -c 1 --depends-on=build_runner -- "dart run build_runner build --delete-conflicting-outputs"
    description: Regenerate code in packages that use build_runner.
  l10n:
    run: melos exec --scope=l10n -- "flutter gen-l10n"
    description: Regenerate AppLocalizations in the l10n package.
