name: socialapp_workspace
publish_to: none

environment:
  sdk: ^3.11.5

workspace:
  - apps/trader
  - packages/core
  - packages/design_system
  - packages/features/auth
  - packages/features/chat
  - packages/features/follow
  - packages/features/post
  - packages/features/preferences
  - packages/features/reaction
  - packages/features/safety
  - packages/features/settings
  - packages/features/trade
  - packages/l10n

dev_dependencies:
  melos: 6.3.3
